kind: pipeline
name: default

steps:
- name: redis_server
  image: redis
  detach: true
  commands:
  - echo "SOME SETTINGS"
  - redis-server

- name: test_sinatra
  image: golang
  commands:
  - curl -sL sinatra:8080

- name: test_redis
  image: redis
  commands:
  - redis-cli -h redis_server ping

services:
- name: sinatra
  image: mcansky/sinatra_hello
