kind: pipeline
name: default

steps:
- name: test
  image: alpine:3.9.4
  environment:
    HOGE: 'hello drone'
  commands:
    - apk add --update build-base
    - echo $HOGE
    - cat ./HelloWorld.txt

- name: notify-slack
  image: plugins/slack
  settings:
    webhook:
      from_secret: webhook_url
