---
kind: pipeline
name: On master

trigger:
  event: [push]
  branch: [master]

steps:
- name: test
  image: alpine
  commands:
  - echo aaaa

---
kind: pipeline
name: On branch

trigger:
  event: [push]
  branch: [hoge-*]

steps:
- name: test
  image: alpine
  commands:
  - echo ${DRONE_BRANCH}