---
kind: pipeline
name: on_push

steps:
  - name: detached
    image: alpine:3.9.4
    detach: true
    commands:
    - echo "YEE"

  - name: test2
    image: alpine:3.9.4
    commands:
    - sleep 3
    - ping -c 5 datached
    - ping -c 5 test2

trigger:
  event:
    - push