---
kind: pipeline
name: on_push

steps:
  - name: detached
    image: alpine:3.9.4
    detach: true
    commands:
    - sleep 3
    - aaaaf

  - name: test2
    image: alpine:3.9.4
    commands:
    - sleep 12

trigger:
  event:
    - push