---
kind: pipeline
name: on_push

steps:
  - name: test
    image: alpine:3.9.4
    detach: true
    environment:
      HOGE: 'hello drone'
    commands:
      - sleep 10
      - echo "ON PUSH"
      - apk add --update build-base
      - echo $HOGE
      - cat ./hello_world.txt

  - name: test2
    image: alpine:3.9.4
    commands:
      - sleep 10
      - echo "ON PUSH 2"

trigger:
  event:
    - push