---
kind: pipeline
name: on_push

steps:
  - name: test
    image: alpine:3.9.4
    environment:
      HOGE: 'hello drone'
    commands:
      - echo "ON PUSH"
      - apk add --update build-base
      - echo $HOGE
      - cat ./hello_world.txt

  - name: notify-slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: webhook_url

trigger:
  event:
    - push

---
kind: pipeline
name: on_push_2

steps:
  - name: test
    image: alpine:3.9.4
    commands:
      - echo "ON PUSH 2"

trigger:
  event:
    - push

---
kind: pipeline
name: on_pull_request

steps:
  - name: test
    image: alpine:3.9.4
    commands:
      - echo "ON PULL REQUEST"

trigger:
  event:
    - pull_request
